/**
 * Per-page continuation scroll: loads the next page's content inline when the
 * user reaches the bottom. Requires feed: true in site.config.js and a pre-built
 * public/feed-index.json generated by scripts/ingest.js.
 */
import { useState, useEffect, useRef } from 'react'
import { useRouter } from 'next/router'
import Link from 'next/link'
import ReactMarkdown from 'react-markdown'


function SectionMeta({ page }) {
  /** Compact metadata bar for a continuation section header. */
  const chips = [...(page.categories || []), ...(page.tags || [])]
  return (
    <div className="feed-section-meta">
      {page.date && <span>{page.date}</span>}
      {page.reading_time && <span>{page.reading_time} min read</span>}
      {chips.map(c => <span key={c} className="chip chip-tag">{c}</span>)}
    </div>
  )
}


export default function PageContinuation() {
  const router = useRouter()
  const [feed, set_feed] = useState(null)
  const [count, set_count] = useState(0)
  const sentinel = useRef(null)

  useEffect(() => {
    const base = router.basePath || ''
    fetch(`${base}/feed-index.json`).then(r => r.json()).then(set_feed).catch(() => set_feed([]))
  }, [])

  const current_url = router.asPath.split('?')[0].replace(/\/$/, '') || '/'
  const current_idx = feed ? feed.findIndex(p => p.url.replace(/\/$/, '') === current_url) : -1
  const has_more = feed != null && current_idx >= 0 && current_idx + count + 1 < feed.length

  useEffect(() => {
    if (!has_more || !sentinel.current) return
    const obs = new IntersectionObserver(
      ([e]) => { if (e.isIntersecting) set_count(n => n + 1) },
      { rootMargin: '300px' }
    )
    obs.observe(sentinel.current)
    return () => obs.disconnect()
  }, [has_more, count])

  if (feed == null || current_idx < 0) return null

  const sections = Array.from({ length: count }, (_, i) => feed[current_idx + 1 + i]).filter(Boolean)

  return (
    <div className="feed-continuation">
      {sections.map(page => (
        <section key={page.url} className="feed-section">
          <div className="feed-section-divider" />
          <h1 className="feed-section-title">
            <Link href={page.url}>{page.title}</Link>
          </h1>
          <SectionMeta page={page} />
          <ReactMarkdown>{page.content}</ReactMarkdown>
        </section>
      ))}
      {has_more && <div ref={sentinel} className="feed-sentinel" />}
    </div>
  )
}
