/**
 * Fetches and renders the full post listing from /posts-index.json.
 * Used on the posts/index.mdx page. Data is generated by scripts/ingest.js.
 */
import { useState, useEffect } from 'react'
import Link from 'next/link'


function fmt_date(date_str) {
  if (!date_str) return ''
  const d = new Date(date_str)
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
}


export default function PostIndex() {
  const [posts, set_posts] = useState(null)

  useEffect(() => {
    fetch('/posts-index.json')
      .then(r => r.json())
      .then(set_posts)
      .catch(() => set_posts([]))
  }, [])

  if (posts === null) return <p className="post-index-loading">Loading posts…</p>
  if (!posts.length)  return <p>No posts found.</p>

  return (
    <div className="post-index">
      {posts.map(post => (
        <div key={post.url} className="post-entry">
          <Link href={post.url} className="post-title">{post.title}</Link>
          <div className="post-meta">
            {post.date && <span>{fmt_date(post.date)}</span>}
            {post.reading_time && <span>{post.reading_time} min read</span>}
          </div>
          {post.categories?.length > 0 && (
            <div className="tag-list">
              {post.categories.map(c => <span key={c} className="chip chip-category">{c}</span>)}
              {post.tags?.map(t => <span key={t} className="chip chip-tag">{t}</span>)}
            </div>
          )}
        </div>
      ))}
    </div>
  )
}
